#!/bin/bash
# token-sweep.sh - mechanical class->token mapping for ZakApp v1.0 design overhaul
# Usage: bash token-sweep.sh <file.tsx> [file2.tsx ...]
# Mapping per docs/plans/v1-design-overhaul-token-migration.md (b1-corrected) + DESIGN.md §7
set -euo pipefail
for f in "$@"; do
  python3 - "$f" <<'EOF'
import sys, re
p = sys.argv[1]
t = open(p).read()
orig = t

# ordered: specific -> general (regex, all occurrences)
pairs = [
    # --- gradients & tinted banners -> neutral/tonal surfaces ---
    (r'(?<![:\w-])bg-gradient-to-r from-teal-50 to-cyan-50 rounded-lg border-2 border-teal-200', 'bg-muted rounded-lg border border-border'),
    (r'(?<![:\w-])bg-gradient-to-r from-blue-50 to-indigo-50', 'bg-accent'),
    (r'(?<![:\w-])border-2 border-blue-200', 'border border-border'),
    (r'(?<![:\w-])bg-gradient-to-br from-green-500 to-green-700', 'bg-secondary'),
    (r'(?<![:\w-])from-green-50 to-emerald-50', 'bg-success-soft'),
    (r'(?<![:\w-])from-amber-50 to-yellow-50', 'bg-warn-soft'),
    (r'(?<![:\w-])from-red-50 to-rose-50', 'bg-danger-soft'),
    # --- headings: gray-800/900 = brand text (DESIGN 7.1 headings=secondary) ---
    # BUT only when used as headings; blanket-mapping gray-900->secondary is wrong for
    # body-on-dark chips. We map gray-900->foreground (body) and headings get text-secondary
    # via the h1-h6 CSS rule + CardTitle sweep. Files overriding with text-gray-900 on
    # h2/h3/h4 elements get caught by the element rule. So: gray-900/800 -> foreground.
    (r'(?<![:\w-])text-gray-900', 'text-foreground'),
    (r'(?<![:\w-])text-gray-800', 'text-foreground'),
    (r'(?<![:\w-])text-gray-700', 'text-foreground/80'),  # reconciled: migration doc (c) text-foreground/80; safe direction + distinct from gray-800
    (r'(?<![:\w-])text-gray-600', 'text-muted-foreground'),
    (r'(?<![:\w-])text-gray-500', 'text-muted-foreground'),
    (r'(?<![:\w-])text-gray-400', 'text-muted-foreground'),  # batch2 review: tertiary fails 2.41:1 on bg; muted is the safe default - hand-apply tertiary only to decorative icons
    (r'(?<![:\w-])text-gray-300', 'text-tertiary'),  # rare (disabled/dividers)
    (r'(?<![:\w-])text-slate-900', 'text-foreground'),
    (r'(?<![:\w-])text-slate-800', 'text-foreground'),
    (r'(?<![:\w-])text-slate-700', 'text-foreground'),
    (r'(?<![:\w-])text-slate-600', 'text-muted-foreground'),
    (r'(?<![:\w-])text-slate-500', 'text-muted-foreground'),
    (r'(?<![:\w-])text-slate-400', 'text-tertiary'),
    (r'(?<![:\w-])text-slate-950', 'text-foreground'),
    (r'(?<![:\w-])text-slate-950/80', 'text-foreground/80'),
    # --- backgrounds ---
    (r'(?<![:\w-])bg-gray-50/50', 'bg-surface-2/50'),
    (r'(?<![:\w-])bg-gray-50/60', 'bg-surface-2/60'),
    (r'(?<![:\w-])bg-gray-50(?![-0-9])', 'bg-muted'),  # contract 7.1: gray-50 -> muted (values identical today)
    (r'(?<![:\w-])bg-gray-100(?![-0-9])', 'bg-muted'),
    (r'(?<![:\w-])bg-gray-200(?![-0-9])', 'bg-muted'),
    (r'(?<![:\w-])bg-gray-300(?![-0-9])', 'bg-border-strong'),
    (r'(?<![:\w-])bg-slate-50(?![-0-9])', 'bg-surface-2'),
    (r'(?<![:\w-])bg-slate-100(?![-0-9])', 'bg-muted'),
    (r'(?<![:\w-])bg-slate-200(?![-0-9])', 'bg-border-strong'),
    (r'(?<![:\w-])bg-white(?![-0-9a-zA-Z])', 'bg-card'),
    # --- borders & dividers ---
    (r'(?<![:\w-])border-gray-100', 'border-border'),
    (r'(?<![:\w-])border-gray-200', 'border-border'),
    (r'(?<![:\w-])border-gray-300', 'border-border-strong'),
    (r'(?<![:\w-])border-slate-100', 'border-border'),
    (r'(?<![:\w-])border-slate-200', 'border-border'),
    (r'(?<![:\w-])border-slate-300', 'border-border-strong'),
    (r'divide-gray-100', 'divide-border'),
    (r'divide-gray-200', 'divide-border'),
    (r'divide-gray-700', 'divide-border-strong'),
    (r'(?<![:\w-])border-slate-950/10', 'border-border'),
    # --- hover states ---
    (r'hover:bg-gray-50', 'hover:bg-muted'),
    (r'hover:bg-gray-100', 'hover:bg-muted'),
    (r'hover:bg-gray-200', 'hover:bg-muted'),
    (r'hover:bg-gray-700', 'hover:bg-muted'),
    (r'hover:bg-gray-800', 'hover:bg-muted'),
    (r'hover:bg-slate-50', 'hover:bg-surface-2'),
    (r'hover:bg-slate-100', 'hover:bg-muted'),
    (r'hover:text-gray-900', 'hover:text-foreground'),
    (r'hover:text-gray-800', 'hover:text-foreground'),
    (r'hover:text-gray-700', 'hover:text-foreground'),
    (r'hover:text-gray-600', 'hover:text-foreground'),
    (r'hover:text-gray-500', 'hover:text-muted-foreground'),
    (r'hover:border-gray-200', 'hover:border-border'),
    (r'hover:border-gray-300', 'hover:border-border-strong'),
    (r'hover:bg-slate-200', 'hover:bg-muted'),
    # --- status: green family -> success ---
    (r'(?<![:\w-])bg-green-50(?![-0-9])', 'bg-success-soft'),
    (r'(?<![:\w-])bg-green-100(?![-0-9])', 'bg-success-soft'),
    (r'(?<![:\w-])bg-green-500(?![-0-9])', 'bg-success'),
    (r'(?<![:\w-])bg-green-600(?![-0-9])', 'bg-success'),
    (r'(?<![:\w-])bg-green-700(?![-0-9])', 'bg-success'),
    (r'(?<![:\w-])text-green-600', 'text-success'),
    (r'(?<![:\w-])text-green-700', 'text-success'),
    (r'(?<![:\w-])text-green-800', 'text-success'),
    (r'(?<![:\w-])text-green-900', 'text-success'),
    (r'(?<![:\w-])text-green-400', 'text-success'),
    (r'(?<![:\w-])border-green-100', 'border-success/20'),
    (r'(?<![:\w-])border-green-200', 'border-success/30'),
    (r'(?<![:\w-])border-green-500', 'border-success'),
    (r'(?<![:\w-])ring-green-500', 'ring-success'),
    (r'hover:bg-green-50', 'hover:bg-success-soft'),
    (r'hover:bg-green-100', 'hover:bg-success-soft'),
    (r'hover:text-green-600', 'hover:text-success'),
    (r'hover:to-green-600', 'hover:to-success'),
    # --- emerald (was the old primary) -> brand tonal/success by value ---
    (r'(?<![:\w-])bg-emerald-50(?![-0-9])', 'bg-accent'),
    (r'(?<![:\w-])bg-emerald-100(?![-0-9])', 'bg-accent'),
    (r'(?<![:\w-])bg-emerald-500(?![-0-9])', 'bg-secondary'),
    (r'(?<![:\w-])bg-emerald-600(?![-0-9])', 'bg-secondary'),
    (r'(?<![:\w-])bg-emerald-700(?![-0-9])', 'bg-secondary'),
    (r'(?<![:\w-])text-emerald-600', 'text-secondary'),
    (r'(?<![:\w-])text-emerald-700', 'text-secondary'),
    (r'(?<![:\w-])text-emerald-800', 'text-secondary'),
    (r'(?<![:\w-])text-emerald-900', 'text-secondary'),
    (r'(?<![:\w-])text-emerald-400', 'text-secondary'),  # batch3 review: was secondary-foreground (1.16:1 on light = invisible); emerald-400 = bright text on dark -> brand
    (r'(?<![:\w-])text-emerald-300', 'text-secondary/80'),
    (r'hover:text-emerald-300', 'hover:text-secondary/80'),
    (r'(?<![:\w-])border-emerald-100', 'border-border'),
    (r'(?<![:\w-])border-emerald-200', 'border-border'),
    (r'(?<![:\w-])border-emerald-500/30', 'border-border'),
    (r'hover:bg-emerald-50', 'hover:bg-accent'),
    (r'hover:bg-emerald-100', 'hover:bg-accent'),
    (r'hover:text-emerald-600', 'hover:text-secondary'),
    (r'(?<![:\w-])from-emerald-500', 'from-secondary'),
    (r'(?<![:\w-])to-emerald-600', 'to-secondary'),
    # --- teal (old brand) -> brand ---
    (r'(?<![:\w-])bg-teal-50(?![-0-9])', 'bg-accent'),
    (r'(?<![:\w-])bg-teal-100(?![-0-9])', 'bg-accent'),
    (r'(?<![:\w-])bg-teal-600(?![-0-9])', 'bg-secondary'),
    (r'(?<![:\w-])bg-teal-700(?![-0-9])', 'bg-secondary'),
    (r'(?<![:\w-])text-teal-600', 'text-secondary'),
    (r'(?<![:\w-])text-teal-700', 'text-secondary'),
    (r'(?<![:\w-])text-teal-800', 'text-secondary'),
    (r'(?<![:\w-])text-teal-900', 'text-secondary'),
    (r'(?<![:\w-])border-teal-100', 'border-border'),
    (r'(?<![:\w-])border-teal-200', 'border-border'),
    (r'(?<![:\w-])border-teal-500', 'border-secondary'),
    (r'(?<![:\w-])ring-teal-500', 'ring-ring'),
    (r'(?<![:\w-])ring-teal-600', 'ring-ring'),
    (r'focus:ring-teal-600', 'focus:ring-ring'),
    (r'hover:bg-teal-50', 'hover:bg-accent'),
    (r'hover:bg-teal-100', 'hover:bg-accent'),
    (r'hover:text-teal-700', 'hover:text-secondary'),
    (r'hover:bg-teal-700', 'hover:bg-secondary/90'),
    (r'(?<![:\w-])from-teal-500', 'from-secondary'),
    (r'(?<![:\w-])to-teal-600', 'to-secondary'),
    (r'shadow-teal-500/20', 'shadow-secondary/20'),
    # --- red -> danger ---
    (r'(?<![:\w-])bg-red-50(?![-0-9])', 'bg-danger-soft'),
    (r'(?<![:\w-])bg-red-100(?![-0-9])', 'bg-danger-soft'),
    (r'(?<![:\w-])bg-red-500(?![-0-9])', 'bg-danger'),
    (r'(?<![:\w-])bg-red-600(?![-0-9])', 'bg-danger'),
    (r'(?<![:\w-])text-red-400', 'text-danger/80'),
    (r'(?<![:\w-])text-red-500', 'text-danger'),
    (r'(?<![:\w-])text-red-600', 'text-danger'),
    (r'(?<![:\w-])text-red-700', 'text-danger'),
    (r'(?<![:\w-])text-red-800', 'text-danger'),
    (r'(?<![:\w-])text-red-900', 'text-danger'),
    (r'(?<![:\w-])border-red-100', 'border-danger/20'),
    (r'(?<![:\w-])border-red-200', 'border-danger/30'),
    (r'(?<![:\w-])border-red-300', 'border-danger/40'),
    (r'(?<![:\w-])border-red-500', 'border-danger'),
    (r'(?<![:\w-])ring-red-500', 'ring-danger'),
    (r'focus:ring-red-500', 'focus:ring-danger'),
    (r'focus:border-red-500', 'focus:border-danger'),
    (r'hover:bg-red-50', 'hover:bg-danger-soft'),
    (r'hover:bg-red-100', 'hover:bg-danger-soft'),
    (r'hover:bg-red-200', 'hover:bg-danger/20'),
    (r'hover:bg-red-600', 'hover:bg-danger/90'),
    (r'hover:text-red-500', 'hover:text-danger'),
    (r'(?<![:\w-])from-red-500', 'from-danger'),
    (r'(?<![:\w-])to-red-600', 'to-danger'),
    # --- blue/indigo/sky/cyan (info) -> brand tonal (NOT amber) ---
    (r'(?<![:\w-])bg-blue-50(?![-0-9])', 'bg-accent'),
    (r'(?<![:\w-])bg-blue-100(?![-0-9])', 'bg-accent'),
    (r'(?<![:\w-])bg-blue-600(?![-0-9])', 'bg-secondary'),
    (r'(?<![:\w-])bg-blue-700(?![-0-9])', 'bg-secondary'),
    (r'(?<![:\w-])text-blue-400', 'text-secondary/80'),
    (r'(?<![:\w-])text-blue-600', 'text-secondary'),
    (r'(?<![:\w-])text-blue-700', 'text-secondary'),
    (r'(?<![:\w-])text-blue-800', 'text-secondary'),
    (r'(?<![:\w-])text-blue-900', 'text-secondary'),
    (r'(?<![:\w-])border-blue-100', 'border-border'),
    (r'(?<![:\w-])border-blue-200', 'border-border'),
    (r'(?<![:\w-])border-blue-300', 'border-border-strong'),
    (r'(?<![:\w-])ring-blue-500', 'ring-ring'),
    (r'focus:ring-blue-500', 'focus:ring-ring'),
    (r'focus:border-blue-500', 'focus:border-ring'),
    (r'hover:bg-blue-50', 'hover:bg-accent'),
    (r'hover:bg-blue-100', 'hover:bg-accent'),
    (r'hover:bg-blue-700', 'hover:bg-secondary/90'),
    (r'hover:text-blue-600', 'hover:text-secondary'),
    (r'(?<![:\w-])bg-indigo-50(?![-0-9])', 'bg-accent'),
    (r'(?<![:\w-])bg-indigo-100(?![-0-9])', 'bg-accent'),
    (r'(?<![:\w-])text-indigo-600', 'text-secondary'),
    (r'(?<![:\w-])text-indigo-700', 'text-secondary'),
    (r'(?<![:\w-])text-indigo-800', 'text-secondary'),
    (r'(?<![:\w-])border-indigo-200', 'border-border'),
    (r'(?<![:\w-])ring-indigo-500', 'ring-ring'),
    (r'focus:ring-indigo-500', 'focus:ring-ring'),
    (r'hover:bg-indigo-50', 'hover:bg-accent'),
    (r'hover:bg-indigo-100', 'hover:bg-accent'),
    (r'(?<![:\w-])bg-sky-50(?![-0-9])', 'bg-accent'),
    (r'(?<![:\w-])bg-sky-100(?![-0-9])', 'bg-accent'),
    (r'(?<![:\w-])text-sky-600', 'text-secondary'),
    (r'(?<![:\w-])text-sky-700', 'text-secondary'),
    (r'(?<![:\w-])bg-cyan-50(?![-0-9])', 'bg-accent'),
    (r'(?<![:\w-])bg-cyan-100(?![-0-9])', 'bg-accent'),
    (r'(?<![:\w-])text-cyan-600', 'text-secondary'),
    (r'(?<![:\w-])text-cyan-700', 'text-secondary'),
    (r'focus:ring-cyan-500', 'focus:ring-ring'),
    # --- amber/yellow/orange (warn family) ---
    (r'(?<![:\w-])bg-amber-50(?![-0-9])', 'bg-warn-soft'),
    (r'(?<![:\w-])bg-amber-100(?![-0-9])', 'bg-warn-soft'),
    (r'(?<![:\w-])bg-amber-200(?![-0-9])', 'bg-warn-soft'),
    (r'(?<![:\w-])text-amber-400', 'text-warn'),
    (r'(?<![:\w-])text-amber-500', 'text-warn'),
    (r'(?<![:\w-])text-amber-600', 'text-warn-strong'),
    (r'(?<![:\w-])text-amber-700', 'text-warn-strong'),
    (r'(?<![:\w-])text-amber-800', 'text-warn-strong'),
    (r'(?<![:\w-])text-amber-900', 'text-warn-strong'),
    (r'(?<![:\w-])border-amber-100', 'border-warn/20'),
    (r'(?<![:\w-])border-amber-200', 'border-warn/30'),
    (r'(?<![:\w-])border-amber-300', 'border-warn/40'),
    (r'(?<![:\w-])border-amber-500', 'border-warn'),
    (r'(?<![:\w-])ring-amber-500', 'ring-warn'),
    (r'focus:ring-amber-500', 'focus:ring-warn'),
    (r'hover:bg-amber-50', 'hover:bg-warn-soft'),
    (r'hover:bg-amber-100', 'hover:bg-warn-soft'),
    (r'(?<![:\w-])bg-yellow-50(?![-0-9])', 'bg-warn-soft'),
    (r'(?<![:\w-])bg-yellow-100(?![-0-9])', 'bg-warn-soft'),
    (r'(?<![:\w-])text-yellow-400', 'text-warn'),
    (r'(?<![:\w-])text-yellow-600', 'text-warn-strong'),
    (r'(?<![:\w-])text-yellow-700', 'text-warn-strong'),
    (r'(?<![:\w-])text-yellow-800', 'text-warn-strong'),
    (r'(?<![:\w-])border-yellow-200', 'border-warn/30'),
    (r'(?<![:\w-])ring-yellow-400', 'ring-warn'),
    (r'hover:bg-yellow-100', 'hover:bg-warn-soft'),
    (r'(?<![:\w-])bg-orange-50(?![-0-9])', 'bg-warn-soft'),
    (r'(?<![:\w-])bg-orange-100(?![-0-9])', 'bg-warn-soft'),
    (r'(?<![:\w-])text-orange-600', 'text-warn-strong'),
    (r'(?<![:\w-])text-orange-700', 'text-warn-strong'),
    (r'(?<![:\w-])border-orange-200', 'border-warn/30'),
    (r'hover:bg-orange-100', 'hover:bg-warn-soft'),
    # --- purple/pink/violet/rose (decorative) -> neutral/brand ---
    (r'(?<![:\w-])bg-purple-50(?![-0-9])', 'bg-accent'),
    (r'(?<![:\w-])bg-purple-100(?![-0-9])', 'bg-accent'),
    (r'(?<![:\w-])text-purple-600', 'text-secondary'),
    (r'(?<![:\w-])text-purple-700', 'text-secondary'),
    (r'(?<![:\w-])text-purple-800', 'text-secondary'),
    (r'(?<![:\w-])border-purple-200', 'border-border'),
    (r'(?<![:\w-])ring-purple-500', 'ring-ring'),
    (r'focus:ring-purple-500', 'focus:ring-ring'),
    (r'hover:bg-purple-50', 'hover:bg-accent'),
    (r'(?<![:\w-])bg-violet-50(?![-0-9])', 'bg-accent'),
    (r'(?<![:\w-])text-violet-600', 'text-secondary'),
    (r'(?<![:\w-])ring-violet-500', 'ring-ring'),
    (r'(?<![:\w-])bg-pink-50(?![-0-9])', 'bg-accent'),
    (r'(?<![:\w-])bg-pink-100(?![-0-9])', 'bg-accent'),
    (r'(?<![:\w-])text-pink-600', 'text-secondary'),
    (r'(?<![:\w-])bg-rose-50(?![-0-9])', 'bg-danger-soft'),
    (r'(?<![:\w-])text-rose-600', 'text-danger'),
    (r'(?<![:\w-])bg-fuchsia-100(?![-0-9])', 'bg-accent'),
    (r'(?<![:\w-])text-fuchsia-700', 'text-secondary'),
    # --- legacy primary/secondary numeric scales (Ikhlas teal/bronze) ---
    # primary = action color: bg-primary-N as BUTTON backgrounds -> bg-primary (amber CTA)
    # primary as TEXT/brand accents -> text-secondary (brand) EXCEPT rationed slots
    # This script maps conservatively: buttons handled by hand, text/bg tonal here.
    (r'(?<![:\w-])bg-primary-50(?![-0-9a-zA-Z])', 'bg-accent'),
    (r'(?<![:\w-])bg-primary-100(?![-0-9a-zA-Z])', 'bg-accent'),
    (r'(?<![:\w-])bg-primary-600(?![-0-9a-zA-Z])', 'bg-primary'),
    (r'(?<![:\w-])bg-primary-700(?![-0-9a-zA-Z])', 'bg-primary'),
    (r'hover:bg-primary-700', 'hover:bg-warn-strong'),
    (r'hover:bg-primary-800', 'hover:bg-warn-strong'),
    (r'(?<![:\w-])text-primary-600', 'text-secondary'),
    (r'(?<![:\w-])text-primary-700', 'text-secondary'),
    (r'(?<![:\w-])text-primary-900', 'text-secondary'),
    (r'(?<![:\w-])border-primary-100', 'border-border'),
    (r'(?<![:\w-])border-primary-200', 'border-border-strong'),
    (r'(?<![:\w-])border-primary-500', 'border-primary'),
    (r'(?<![:\w-])ring-primary-500', 'ring-ring'),
    (r'focus:ring-primary-500', 'focus:ring-ring'),
    (r'hover:bg-primary-50', 'hover:bg-accent'),
    (r'hover:text-primary-900', 'hover:text-secondary'),
    (r'(?<![:\w-])from-primary-50', 'from-accent'),
    (r'(?<![:\w-])from-primary-500', 'from-primary'),
    (r'(?<![:\w-])to-primary-600', 'to-primary'),
    (r'(?<![:\w-])text-secondary-900', 'text-warn-strong'),
    (r'(?<![:\w-])border-secondary-200', 'border-border'),
    (r'(?<![:\w-])bg-secondary-500(?![-0-9a-zA-Z])', 'bg-primary'),
    (r'shadow-primary-700/20', 'shadow-primary/20'),
    (r'focus:ring-emerald-500', 'focus:ring-ring'),
    (r'focus:border-emerald-500', 'focus:border-ring'),
    (r'border-emerald-500(?![-0-9a-zA-Z])', 'border-secondary'),
    (r'ring-emerald-500', 'ring-ring'),
    (r'text-orange-800', 'text-warn-strong'),
    (r'text-orange-900', 'text-warn-strong'),
    (r'border-blue-500(?![-0-9a-zA-Z])', 'border-primary'),  # selected-state borders -> primary per batch-3 hand-fix
    (r'text-green-500', 'text-success'),
    (r'text-indigo-900', 'text-secondary'),
    (r'text-yellow-900', 'text-warn-strong'),
    (r'bg-red-700(?![-0-9a-zA-Z])', 'bg-danger'),
    (r'bg-amber-700(?![-0-9a-zA-Z])', 'bg-warn-strong'),
    (r'border-teal-300', 'border-border-strong'),
    (r'text-teal-500', 'text-secondary'),
    (r'bg-teal-500(?![-0-9a-zA-Z])', 'bg-secondary'),
    (r'dark:bg-gray-800', ''),  # strip: no leading-space requirement
    (r'bg-emerald-200(?![-0-9])', 'bg-accent'),
    (r'hover\:bg-gray-200:hover', 'hover:bg-muted:hover'),
    (r'text-blue-500', 'text-secondary'),
    (r'text-blue-400', 'text-secondary/80'),

    # --- dark: dual-theme pairs: tokens are dual-theme; strip dark: variants of mapped classes ---
    (r' dark:bg-gray-800', ''),
    (r' dark:bg-gray-700', ''),
    (r' dark:bg-gray-600', ''),
    (r' dark:text-gray-100', ''),
    (r' dark:text-gray-300', ''),
    (r' dark:text-gray-400', ''),
    (r' dark:border-gray-600', ''),
    (r' dark:border-gray-700', ''),
    (r' dark:hover:bg-gray-700', ''),
    (r' dark:hover:text-gray-200', ''),
    (r' dark:bg-slate-800', ''),
    (r' dark:text-slate-200', ''),
    (r' dark:text-slate-400', ''),
    # cleanup double spaces
]
for old, new in pairs:
    t = re.sub(old, new, t)
t = re.sub(r'(?<=[\w\]\)"]) {2,}(?=[\w\]\)"])', ' ', t)
if t != orig:
    open(p, 'w').write(t)
    print(f"swept {p}")
else:
    print(f"nochange {p}")
EOF
done
