
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { NisabYearRecord } from '../types/nisabYearRecord';
import { PaymentRecord } from '@zakapp/shared/types/tracking';
import { Asset } from '../types/index';
// import { formatCurrency } from './formatters'; // Avoid circular dependency if simple

// Simple local formatter to avoid complex imports if needed, or import standard one
const formatCurrency = (amount: number, currency = 'USD') => {
    return new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency,
    }).format(amount);
};

export class ReportGenerator {
    private doc: jsPDF;
    private readonly MARGIN = 15;
    private readonly BRAND_COLOR = '#0f766e'; // teal-700

    constructor() {
        this.doc = new jsPDF();
    }

    private addHeader(title: string, subtitle?: string) {
        const doc = this.doc;
        const pageWidth = doc.internal.pageSize.width;

        // Brand Name
        doc.setFontSize(22);
        doc.setTextColor(this.BRAND_COLOR);
        doc.setFont('helvetica', 'bold');
        doc.text('ZakApp', this.MARGIN, 20);

        // Document Title
        doc.setFontSize(16);
        doc.setTextColor(40);
        doc.setFont('helvetica', 'normal');
        const titleWidth = doc.getTextWidth(title);
        doc.text(title, pageWidth - this.MARGIN - titleWidth, 20);

        // Line
        doc.setDrawColor(200);
        doc.line(this.MARGIN, 25, pageWidth - this.MARGIN, 25);

        // Subtitle / Date
        if (subtitle) {
            doc.setFontSize(10);
            doc.setTextColor(100);
            doc.text(subtitle, this.MARGIN, 32);
        }
    }

    private addFooter() {
        const doc = this.doc;
        const pageHeight = doc.internal.pageSize.height;
        const pageWidth = doc.internal.pageSize.width;

        doc.setFontSize(8);
        doc.setTextColor(150);
        const text = `Generated by ZakApp on ${new Date().toLocaleDateString()} - Local-First Privacy`;
        doc.text(text, this.MARGIN, pageHeight - 10);

        // Page Numbers
        const pageCount = doc.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.text(`Page ${i} of ${pageCount}`, pageWidth - this.MARGIN - 20, pageHeight - 10);
        }
    }

    public generateHawlStatement(record: NisabYearRecord, assets: Asset[], username: string = 'User') {
        const doc = this.doc;

        // Header
        const hijri = record.hijriYear ? `${record.hijriYear} AH` : 'Current Year';
        this.addHeader('Zakat Hawl Statement', `Record ID: ${record.id.slice(0, 8)}... | ${hijri}`);

        // Summary Section
        let yPos = 45;
        doc.setFontSize(14);
        doc.setTextColor(0);
        doc.text('Summary', this.MARGIN, yPos);
        yPos += 10;

        const summaryData = [
            ['Beneficiary', username],
            ['Hawl Period', `${new Date(record.hawlStartDate!).toLocaleDateString()} - ${record.hawlCompletionDate ? new Date(record.hawlCompletionDate).toLocaleDateString() : 'Ongoing'}`],
            ['Nisab Threshold', formatCurrency(Number(record.nisabThreshold || 0))],
            ['Status', record.status || 'DRAFT']
        ];

        autoTable(doc, {
            startY: yPos,
            head: [],
            body: summaryData,
            theme: 'plain',
            styles: { fontSize: 10, cellPadding: 2 },
            columnStyles: { 0: { fontStyle: 'bold', width: 40 } },
            margin: { left: this.MARGIN }
        });

        // Financials Section
        const financialsY = (doc as any).lastAutoTable.finalY + 15;
        doc.setFontSize(14);
        doc.text('Calculation Details', this.MARGIN, financialsY);

        const financialsData = [
            ['Total Assets', formatCurrency(Number(record.totalWealth || 0))],
            ['Zakatable Assets', formatCurrency(Number(record.zakatableWealth || 0))],
            ['Total Liabilities', '(Deducted)'], // TODO: pass actual liability total if available
            ['Net Zakatable Wealth', formatCurrency(Number(record.zakatableWealth || 0))], // Assuming net passed in record
            ['Zakat Due (2.5%)', formatCurrency(Number(record.zakatAmount || 0))]
        ];

        autoTable(doc, {
            startY: financialsY + 5,
            head: [['Item', 'Amount']],
            body: financialsData,
            theme: 'striped',
            headStyles: { fillColor: this.BRAND_COLOR },
            margin: { left: this.MARGIN }
        });

        // Disclaimer
        const disclaimerY = (doc as any).lastAutoTable.finalY + 20;
        doc.setFontSize(8);
        doc.setTextColor(100);
        doc.text('This document is a record of your Zakat calculation based on the assets provided.', this.MARGIN, disclaimerY);
        doc.text('Verifying the accuracy of assets and market values is the user\'s responsibility.', this.MARGIN, disclaimerY + 5);

        this.addFooter();
        doc.save(`ZakApp_Hawl_Statement_${hijri}.pdf`);
    }

    public generatePaymentSummary(payments: PaymentRecord[], year?: number) {
        const doc = this.doc;
        const title = year ? `Zakat Payments - ${year}` : 'Zakat Payment History';
        this.addHeader(title, `Total Records: ${payments.length}`);

        const tableData = payments.map(p => [
            new Date(p.paymentDate).toLocaleDateString(),
            p.recipientName || 'Unspecified',
            p.recipientCategory || 'General',
            formatCurrency(Number(p.amount)),
            p.notes || '-'
        ]);

        // Calculate Total
        const total = payments.reduce((sum, p) => sum + (Number(p.amount) || 0), 0);
        tableData.push(['', '', 'TOTAL', formatCurrency(total), '']);
        autoTable(doc, {
            startY: 40,
            head: [['Date', 'Recipient', 'Category', 'Amount', 'Notes']],
            body: tableData,
            headStyles: { fillColor: this.BRAND_COLOR },
            columnStyles: { 3: { halign: 'right', fontStyle: 'bold' } },
            margin: { left: this.MARGIN },
            didParseCell: (data) => {
                // Bold the total row
                if (data.row.index === tableData.length - 1) {
                    data.cell.styles.fontStyle = 'bold';
                    data.cell.styles.fillColor = [240, 240, 240];
                }
            }
        });

        this.addFooter();
        const filename = year ? `ZakApp_Payments_${year}.pdf` : 'ZakApp_Payments_All.pdf';
        doc.save(filename);
    }
}
