/**
 * Copyright (c) 2024 ZakApp Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */


import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { NisabYearRecord } from '../types/nisabYearRecord';
import { PaymentRecord } from '@zakapp/shared/types/tracking';
import { Asset } from '../types/index';
// import { formatCurrency } from './formatters'; // Avoid circular dependency if simple

// Simple local formatter to avoid complex imports if needed, or import standard one
const formatCurrency = (amount: number, currency = 'USD') => {
    return new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency,
    }).format(amount);
};

export class ReportGenerator {
    private doc: jsPDF;
    private readonly MARGIN = 15;
    private readonly BRAND_COLOR = '#0f766e'; // teal-700

    constructor() {
        this.doc = new jsPDF();
    }

    private addHeader(title: string, subtitle?: string) {
        const doc = this.doc;
        const pageWidth = doc.internal.pageSize.width;

        // Brand Name
        doc.setFontSize(22);
        doc.setTextColor(this.BRAND_COLOR);
        doc.setFont('helvetica', 'bold');
        doc.text('ZakApp', this.MARGIN, 20);

        // Document Title
        doc.setFontSize(16);
        doc.setTextColor(40);
        doc.setFont('helvetica', 'normal');
        const titleWidth = doc.getTextWidth(title);
        doc.text(title, pageWidth - this.MARGIN - titleWidth, 20);

        // Line
        doc.setDrawColor(200);
        doc.line(this.MARGIN, 25, pageWidth - this.MARGIN, 25);

        // Subtitle / Date
        if (subtitle) {
            doc.setFontSize(10);
            doc.setTextColor(100);
            doc.text(subtitle, this.MARGIN, 32);
        }
    }

    private addFooter() {
        const doc = this.doc;
        const pageHeight = doc.internal.pageSize.height;
        const pageWidth = doc.internal.pageSize.width;

        doc.setFontSize(8);
        doc.setTextColor(150);
        const text = `Generated by ZakApp on ${new Date().toLocaleDateString()} - Local-First Privacy`;
        doc.text(text, this.MARGIN, pageHeight - 10);

        // Page Numbers
        const pageCount = doc.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.text(`Page ${i} of ${pageCount}`, pageWidth - this.MARGIN - 20, pageHeight - 10);
        }
    }

    public generateHawlStatement(record: NisabYearRecord, assets: Asset[], username: string = 'User', totalLiabilities: number = 0) {
        const doc = this.doc;

        // Header
        const hijri = record.hijriYear ? `${record.hijriYear} AH` : 'Current Year';
        this.addHeader('Zakat Hawl Statement', `Record ID: ${record.id.slice(0, 8)}... | ${hijri}`);

        // Summary Section
        let yPos = 45;
        doc.setFontSize(14);
        doc.setTextColor(0);
        doc.text('Summary', this.MARGIN, yPos);
        yPos += 10;

        const totalAssets = assets.reduce((sum, a) => sum + Number(a.value || 0), 0);
        const netWorth = totalAssets - totalLiabilities;

        const summaryData = [
            ['Beneficiary', username],
            ['Hawl Period', `${new Date(record.hawlStartDate!).toLocaleDateString()} - ${record.hawlCompletionDate ? new Date(record.hawlCompletionDate).toLocaleDateString() : 'Ongoing'}`],
            ['Nisab Threshold', formatCurrency(Number(record.nisabThreshold || 0))],
            ['Status', record.status || 'DRAFT'],
            ['Total Assets', formatCurrency(totalAssets)],
            ['Total Liabilities', formatCurrency(totalLiabilities)],
            ['Net Worth', formatCurrency(netWorth)]
        ];

        autoTable(doc, {
            startY: yPos,
            head: [],
            body: summaryData,
            theme: 'plain',
            styles: { fontSize: 10, cellPadding: 2 },
            columnStyles: { 0: { fontStyle: 'bold', cellWidth: 40 } },
            margin: { left: this.MARGIN }
        });

        // Financials Section
        const financialsY = (doc as any).lastAutoTable.finalY + 15;
        doc.setFontSize(14);
        doc.text('Calculation Details', this.MARGIN, financialsY);

        const netZakatableWealth = Math.max(0, totalAssets - totalLiabilities);
        
        const financialsData = [
            ['Total Assets', formatCurrency(totalAssets)],
            ['Zakatable Assets', formatCurrency(Number(record.zakatableWealth || 0))],
            ['Total Liabilities', formatCurrency(totalLiabilities)],
            ['Net Zakatable Wealth', formatCurrency(netZakatableWealth)],
            ['Zakat Due (2.5%)', formatCurrency(Number(record.zakatAmount || 0))]
        ];

        autoTable(doc, {
            startY: financialsY + 5,
            head: [['Item', 'Amount']],
            body: financialsData,
            theme: 'striped',
            headStyles: { fillColor: this.BRAND_COLOR },
            margin: { left: this.MARGIN }
        });

        // Disclaimer
        const disclaimerY = (doc as any).lastAutoTable.finalY + 20;
        doc.setFontSize(8);
        doc.setTextColor(100);
        doc.text('This document is a record of your Zakat calculation based on the assets provided.', this.MARGIN, disclaimerY);
        doc.text('Verifying the accuracy of assets and market values is the user\'s responsibility.', this.MARGIN, disclaimerY + 5);

        this.addFooter();
        doc.save(`ZakApp_Hawl_Statement_${hijri}.pdf`);
    }

    public generatePaymentSummary(payments: PaymentRecord[], year?: number) {
        const doc = this.doc;
        const title = year ? `Zakat Payments - ${year}` : 'Zakat Payment History';
        this.addHeader(title, `Total Records: ${payments.length}`);

        const tableData = payments.map(p => [
            new Date(p.paymentDate).toLocaleDateString(),
            p.recipientName || 'Unspecified',
            p.recipientCategory || 'General',
            formatCurrency(Number(p.amount)),
            p.notes || '-'
        ]);

        // Calculate Total
        const total = payments.reduce((sum, p) => sum + (Number(p.amount) || 0), 0);
        tableData.push(['', '', 'TOTAL', formatCurrency(total), '']);
        autoTable(doc, {
            startY: 40,
            head: [['Date', 'Recipient', 'Category', 'Amount', 'Notes']],
            body: tableData,
            headStyles: { fillColor: this.BRAND_COLOR },
            columnStyles: { 3: { halign: 'right', fontStyle: 'bold' } },
            margin: { left: this.MARGIN },
            didParseCell: (data) => {
                // Bold the total row
                if (data.row.index === tableData.length - 1) {
                    data.cell.styles.fontStyle = 'bold';
                    data.cell.styles.fillColor = [240, 240, 240];
                }
            }
        });

        this.addFooter();
        const filename = year ? `ZakApp_Payments_${year}.pdf` : 'ZakApp_Payments_All.pdf';
        doc.save(filename);
    }
    public generateMethodologyReport() {
        const doc = this.doc;
        this.addHeader('Zakat Methodology Report', 'Fiqh Rules & Calculation Logic');

        const yPos = 40;
        doc.setFontSize(11);
        doc.setTextColor(0);

        const sections = [
            {
                title: '1. Nisab Threshold (The Minimum Standard)',
                content: [
                    'The Nisab is the minimum amount of wealth a Muslim must possess for a full lunar year (Hawl) before Zakat becomes obligatory.',
                    'Standard Used: Silver Standard (612.36 grams of silver).',
                    'Reasoning: The Silver Standard is safer for the poor (beneficiaries) as it has a lower threshold, making more people liable to pay Zakat, thus increasing community support. This aligns with the "Precautionary View" (Ahwat) in Islamic jurisprudence.'
                ]
            },
            {
                title: '2. Asset Declarations',
                content: [
                    'Cash & Bank Balances: Zakatable at 100% of value.',
                    'Gold & Silver: Zakatable at 100% of market weight value.',
                    'Jewelry (Personal Use):',
                    '   - Hanafi View: All gold/silver jewelry is Zakatable.',
                    '   - Shafi\'i/Maliki View: Jewelry for personal use is exempt.',
                    '   * ZakApp currently applies the user\'s selected Madhab setting (Default: Hanafi - Safer/Standard).'
                ]
            },
            {
                title: '3. Retirement Accounts (401k/IRA)',
                content: [
                    'Method: "Net Withdrawable Amount" (Majority Opinion).',
                    'Logic: Zakat is due only on the amount accessible to you today.',
                    'Formula: (Market Value - Penalties - Taxes) * 2.5%.',
                    'Note: ZakApp deducts a standard 30% for taxes/penalties if exact figures are not provided.'
                ]
            },
            {
                title: '4. Liabilities & Debts',
                content: [
                    'Immediate Debts: Deductible (Due within 12 lunar months).',
                    'Long-Term Debts (Mortgages): Only the current year\'s payments are deductible.',
                    'Reasoning: Deducting the entire principal of a 30-year loan would consistently zero out wealth, negating the purpose of Zakat.'
                ]
            },
            {
                title: '5. Zakat Rate',
                content: [
                    'Rate: 2.5% (1/40th) of total Zakatable Net Wealth.',
                    'Calculation: (Total Assets - Deductible Liabilities) * 0.025.'
                ]
            }
        ];

        let cursorY = yPos;
        const pageHeight = doc.internal.pageSize.height;

        sections.forEach(section => {
            // Check for page break
            if (cursorY > pageHeight - 60) {
                doc.addPage();
                cursorY = 20;
            }

            // Title
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(this.BRAND_COLOR);
            doc.text(section.title, this.MARGIN, cursorY);
            cursorY += 7;

            // Content
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(50);

            section.content.forEach(line => {
                const splitText = doc.splitTextToSize(line, 180);
                doc.text(splitText, this.MARGIN + 5, cursorY);
                cursorY += (doc.getTextDimensions(splitText).h + 2);
            });

            cursorY += 8; // Spacing between sections
        });

        this.addFooter();
        doc.save('ZakApp_Methodology_Report.pdf');
    }
}
