/**
 * Copyright (c) 2024 ZakApp Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */


import jsPDF from 'jspdf';
import { PDF_THEME, TABLE_STYLES, hex } from './pdfTheme';
import autoTable from 'jspdf-autotable';
import { NisabYearRecord } from '../types/nisabYearRecord';
import { PaymentRecord } from '@zakapp/shared/types/tracking';
import { Asset } from '../types/index';
import { formatCurrency as canonicalCurrency } from './formatters';
// import { formatCurrency } from './formatters'; // Avoid circular dependency if simple

// Simple local formatter to avoid complex imports if needed, or import standard one
const formatCurrency = (amount: number, currency = 'USD') =>
  canonicalCurrency(amount, currency);

export class ReportGenerator {
    private doc: jsPDF;
    private readonly MARGIN = 15;
    // Brand colour now comes from the shared PDF theme (Nur secondary),
    // so reports agree with the app and with each other. Was teal-700 #0f766e.
    private readonly BRAND_COLOR = hex(PDF_THEME.brand);
    private currency: string;

    constructor(currency: string = 'USD') {
        this.doc = new jsPDF();
        this.currency = currency;
    }

    private addHeader(title: string, subtitle?: string) {
        const doc = this.doc;
        const pageWidth = doc.internal.pageSize.width;

        // Brand Name
        doc.setFontSize(22);
        doc.setTextColor(this.BRAND_COLOR);
        doc.setFont('helvetica', 'bold');
        doc.text('ZakApp', this.MARGIN, 20);

        // Document Title
        doc.setFontSize(16);
        doc.setTextColor(...PDF_THEME.ink);
        doc.setFont('helvetica', 'normal');
        const titleWidth = doc.getTextWidth(title);
        doc.text(title, pageWidth - this.MARGIN - titleWidth, 20);

        // Line
        doc.setDrawColor(...PDF_THEME.border);
        doc.line(this.MARGIN, 25, pageWidth - this.MARGIN, 25);

        // Subtitle / Date
        if (subtitle) {
            doc.setFontSize(10);
            doc.setTextColor(...PDF_THEME.inkSoft);
            doc.text(subtitle, this.MARGIN, 32);
        }
    }

    private addFooter() {
        const doc = this.doc;
        const pageHeight = doc.internal.pageSize.height;
        const pageWidth = doc.internal.pageSize.width;

        doc.setFontSize(8);
        doc.setTextColor(...PDF_THEME.inkSoft);
        const text = `Generated by ZakApp on ${new Date().toLocaleDateString()} - Local-First Privacy`;
        doc.text(text, this.MARGIN, pageHeight - 10);

        // Page Numbers
        const pageCount = doc.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.text(`Page ${i} of ${pageCount}`, pageWidth - this.MARGIN - 20, pageHeight - 10);
        }
    }

    public generateHawlStatement(record: NisabYearRecord, assets: Asset[], username: string = 'User', totalLiabilities: number = 0) {
        const doc = this.doc;

        // Header
        const hijri = record.hijriYear ? `${record.hijriYear} AH` : 'Current Year';
        this.addHeader('Zakat Hawl Statement', `Record ID: ${record.id.slice(0, 8)}... | ${hijri}`);

        // Summary Section
        let yPos = 45;
        doc.setFontSize(14);
        doc.setTextColor(...PDF_THEME.ink);
        doc.text('Summary', this.MARGIN, yPos);
        yPos += 10;

        const totalAssets = assets.reduce((sum, a) => sum + Number(a.value || 0), 0);
        const netWorth = totalAssets - totalLiabilities;

        // The recorded threshold may be encrypted (a non-numeric string), in which
        // case it cannot be read here - see the same caveat in NisabComparisonWidget.
        // Printing a hardcoded 0 in its place put "$0.00" on a FINALIZED statement
        // showing a zakat amount due, which reads as a broken calculation. When the
        // value is not readable the row is OMITTED: a missing row is honest, a
        // confident zero is not.
        const rawThreshold = record.nisabThresholdAtStart ?? (record as any).nisabThreshold ?? record.initialNisabThreshold;
        const parsedThreshold = parseFloat(String(rawThreshold ?? ''));
        const thresholdLine: [string, string][] = Number.isFinite(parsedThreshold)
            ? [['Nisab Threshold', formatCurrency(parsedThreshold, this.currency)]]
            : [];

        const summaryData = [
            ['Beneficiary', username],
            ['Hawl Period', `${new Date(record.hawlStartDate!).toLocaleDateString()} - ${record.hawlCompletionDate ? new Date(record.hawlCompletionDate).toLocaleDateString() : 'Ongoing'}`],
            ...thresholdLine,
            ['Status', record.status || 'DRAFT'],
            ['Total Assets', formatCurrency(totalAssets, this.currency)],
            ['Total Liabilities', formatCurrency(totalLiabilities, this.currency)],
            ['Net Worth', formatCurrency(netWorth, this.currency)]
        ];

        autoTable(doc, {
            startY: yPos,
            head: [],
            body: summaryData,
            theme: 'plain',
            styles: { fontSize: 10, cellPadding: 2 },
            columnStyles: { 0: { fontStyle: 'bold', cellWidth: 45 } },
            // Right-align ONLY the monetary rows. A blanket right-align on this
            // column also pushed the name, the hawl dates and the status to the
            // right, which reads wrong for a label/value list.
            didParseCell: (data) => {
                const isMoney = /^[^0-9]*[0-9][0-9,]*\.[0-9]{2}$/.test(String(data.cell.raw ?? ''));
                if (data.section === 'body' && data.column.index === 1 && isMoney) {
                    data.cell.styles.halign = 'right';
                }
            },
            margin: { left: this.MARGIN }
        });

        // Financials Section
        const financialsY = (doc as any).lastAutoTable.finalY + 15;
        doc.setFontSize(14);
        doc.text('Calculation Details', this.MARGIN, financialsY);

        const netZakatableWealth = Math.max(0, totalAssets - totalLiabilities);
        
        const financialsData = [
            ['Total Assets', formatCurrency(totalAssets, this.currency)],
            ['Zakatable Assets', formatCurrency(Number(record.zakatableWealth || 0), this.currency)],
            ['Total Liabilities', formatCurrency(totalLiabilities, this.currency)],
            ['Net Zakatable Wealth', formatCurrency(netZakatableWealth, this.currency)],
            ['Zakat Due (2.5%)', formatCurrency(Number(record.zakatAmount || 0), this.currency)]
        ];

        autoTable(doc, {
            startY: financialsY + 5,
            head: [['Item', 'Amount']],
            body: financialsData,
            ...TABLE_STYLES,
            theme: 'striped',
            columnStyles: { 0: { cellWidth: 90 }, 1: { halign: 'right' } },
            margin: { left: this.MARGIN }
        });

        // Disclaimer
        const disclaimerY = (doc as any).lastAutoTable.finalY + 20;
        doc.setFontSize(8);
        doc.setTextColor(...PDF_THEME.inkSoft);
        doc.text('This document is a record of your Zakat calculation based on the assets provided.', this.MARGIN, disclaimerY);
        doc.text('Verifying the accuracy of assets and market values is the user\'s responsibility.', this.MARGIN, disclaimerY + 5);

        this.addFooter();
        doc.save(`ZakApp_Hawl_Statement_${hijri}.pdf`);
    }

    public generatePaymentSummary(payments: PaymentRecord[], year?: number) {
        const doc = this.doc;
        const title = year ? `Zakat Payments - ${year}` : 'Zakat Payment History';
        this.addHeader(title, `Total Records: ${payments.length}`);

        const tableData = payments.map(p => [
            new Date(p.paymentDate).toLocaleDateString(),
            p.recipientName || 'Unspecified',
            p.recipientCategory || 'General',
            formatCurrency(Number(p.amount), this.currency),
            p.notes || '-'
        ]);

        // Calculate Total
        const total = payments.reduce((sum, p) => sum + (Number(p.amount) || 0), 0);
        tableData.push(['', '', 'TOTAL', formatCurrency(total, this.currency), '']);
        autoTable(doc, {
            startY: 40,
            head: [['Date', 'Recipient', 'Category', 'Amount', 'Notes']],
            body: tableData,
            ...TABLE_STYLES,
            columnStyles: { 3: { halign: 'right', fontStyle: 'bold' } },
            margin: { left: this.MARGIN },
            didParseCell: (data) => {
                // Bold the total row
                if (data.row.index === tableData.length - 1) {
                    data.cell.styles.fontStyle = 'bold';
                    data.cell.styles.fillColor = PDF_THEME.surface2;
                }
            }
        });

        this.addFooter();
        const filename = year ? `ZakApp_Payments_${year}.pdf` : 'ZakApp_Payments_All.pdf';
        doc.save(filename);
    }
}
