import { z } from 'zod';
export declare const baseAssetSchema: any;
export declare const cashAssetSchema: any;
export declare const goldAssetSchema: any;
export declare const silverAssetSchema: any;
export declare const businessAssetSchema: any;
export declare const propertyAssetSchema: any;
export declare const stocksAssetSchema: any;
export declare const cryptoAssetSchema: any;
export declare const debtsAssetSchema: any;
export declare const expensesAssetSchema: any;
export declare const assetSchema: any;
export declare const genericAssetSchema: any;
export declare const assetCategorySchema: any;
export declare const assetFormSchema: any;
export declare const createAssetRequestSchema: any;
export declare const updateAssetRequestSchema: any;
export type CashAssetZod = z.infer<typeof cashAssetSchema>;
export type GoldAssetZod = z.infer<typeof goldAssetSchema>;
export type SilverAssetZod = z.infer<typeof silverAssetSchema>;
export type BusinessAssetZod = z.infer<typeof businessAssetSchema>;
export type PropertyAssetZod = z.infer<typeof propertyAssetSchema>;
export type StocksAssetZod = z.infer<typeof stocksAssetSchema>;
export type CryptoAssetZod = z.infer<typeof cryptoAssetSchema>;
export type DebtsAssetZod = z.infer<typeof debtsAssetSchema>;
export type AssetUnion = z.infer<typeof assetSchema>;
export type GenericAsset = z.infer<typeof genericAssetSchema>;
export type AssetFormData = z.infer<typeof assetFormSchema>;
export type CreateAssetRequest = z.infer<typeof createAssetRequestSchema>;
export type UpdateAssetRequest = z.infer<typeof updateAssetRequestSchema>;
export type AssetCategoryData = z.infer<typeof assetCategorySchema>;
//# sourceMappingURL=schemas.d.ts.map